name: test
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    container: #apfsds9/ubuntu24.04-ros2:latest
      image: ros:jazzy
    steps:
      - uses: actions/checkout@v3
      - name: build and talker and listener test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg2/
          cd /root/ros2_ws
          bash ./src/mypkg2/test/talker_test.bash /root
          bash ./src/mypkg2/test/listener_test.bash /root
