name: test
on: push
jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: ros:jazzy
    steps:
      - uses: actions/checkout@v3
      - name: build / talker and listener test
        shell: bash
        run: |
          apt-get update
          apt-get install -y rsync
          source /opt/ros/jazzy/setup.bash
          mkdir -p /root/ros2_ws1/src/mypkg2
          rsync -av ./ /root/ros2_ws1/src/mypkg2/
          cd /root/ros2_ws
          colcon build
          bash ./src/mypkg2/test/talker_test.bash /root
          bash ./src/mypkg2/test/listener_test.bash /root
